spring:
  application:
    name: seuneuseu



  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true
    properties:
      hibernate.hibernate.format_sql: true
    open-in-view: false

  config:
    import: classpath:application-sec.yaml

#logging:
#  level:
#    org:
#      springframework:
#        security: DEBUG