spring:
  application:
    name: seuneuseu
  profiles:
    active: sec-dev



  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true
    properties:
      hibernate.hibernate.format_sql: true
    open-in-view: false


#logging:
#  level:
#    org:
#      springframework:
#        security: DEBUG