spring:
  application:
    name: seuneuseu

  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

    show-sql: true
    properties:
      hibernate.dialect: org.hibernate.dialect.MySQL8Dialect
      hibernate.hibernate.format_sql: true



  config:
    import: application-sec-pro.yaml

server:
  port: 8080