name: 스프링부트 프로젝트 빌드 후 오라클 클라우드 인스턴스로 배포

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: 코드 체크아웃
        uses: actions/checkout@v4

      - name: JDK 21 설정
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: application-sec.yaml 파일 생성
        run: |
          echo "${{ secrets.APPLICATION_SEC_YAML }}" > application-sec.yaml
          chmod 600 application-sec.yaml

      - name: Gradlew 실행 권한 부여
        run: chmod +x gradlew

      - name: Gradle 빌드
        run: ./gradlew bootJar -x test

      - name: SSH 키 설정
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

      - name: 빌드 파일 및 application-sec.yaml EC2 전송
        run: |
          scp -o StrictHostKeyChecking=no build/libs/seuneuseu-0.0.1-SNAPSHOT.jar ec2-user@${{ secrets.SERVER_HOST }}:/home/ubuntu/app.jar
          scp -o StrictHostKeyChecking=no application-sec.yaml ec2-user@${{ secrets.SERVER_HOST }}:/home/ubuntu/application-sec.yaml

      - name: EC2에서 실행 (기존 프로세스 종료 및 재시작)
        run: |
          ssh -o StrictHostKeyChecking=no ubuntu@${{ secrets.SERVER_HOST }} << 'EOF'
            pkill -f 'java -jar /home/ec2-user/app.jar' || true
            nohup java -jar /home/ubuntu/app.jar --spring.config.additional-location=/home/ubuntu/application-sec.yaml > /home/ec2-user/app.log 2>&1 &
          EOF
